#pragma once

#include <lib/mmio/mmio_macros.h>
#include <lib/stdbool.h>

#include "tmu_map.h"

// 5.4.4.1 - 682

#define TMU_TMHTATR_OFFSET 0x14UL

#define TMHTATR_VALUE_STRUCT_NAME TmuTmhtatrValue

MMIO_DECLARE_REG32_VALUE_STRUCT(TMHTATR_VALUE_STRUCT_NAME);

MMIO_DECLARE_REG32_READER(TMU, TMHTATR, TMHTATR_VALUE_STRUCT_NAME,
						  TMU_TMHTATR_OFFSET);

MMIO_DECLARE_REG32_WRITER(TMU, TMHTATR, TMHTATR_VALUE_STRUCT_NAME,
						  TMU_TMHTATR_OFFSET);

// Helper
#define TMHTATR_DECLARE_BIT_FIELD_FNS(bf_name, T)                             \
	TMU_DECLARE_BIT_FIELD_GETTER(TMHTATR, bf_name, TMHTATR_VALUE_STRUCT_NAME, \
								 T, bf_name##_SHIFT, bf_name##_MASK);         \
	TMU_DECLARE_BIT_FIELD_SETTER(TMHTATR, bf_name, TMHTATR_VALUE_STRUCT_NAME, \
								 T, bf_name##_SHIFT, bf_name##_MASK);

#define EN1_SHIFT 31
#define EN1_MASK (0b1u << EN1_SHIFT)
TMHTATR_DECLARE_BIT_FIELD_FNS(EN1, bool);

#define EN0_SHIFT 30
#define EN0_MASK (0b1u << EN0_SHIFT)
TMHTATR_DECLARE_BIT_FIELD_FNS(EN0, bool);

#define TEMP1_SHIFT 16
#define TEMP1_MASK (0xFFu << TEMP1_SHIFT)
TMHTATR_DECLARE_BIT_FIELD_FNS(TEMP1, int8);

#define TEMP0_SHIFT 0
#define TEMP0_MASK (0xFFu << TEMP0_SHIFT)
TMHTATR_DECLARE_BIT_FIELD_FNS(TEMP0, int8);
