#pragma once

#include <lib/mmio/mmio_macros.h>
#include <lib/stdbool.h>

#include "tmu_map.h"

// 5.4.4.1 - 682

#define TMU_TMHTITR_OFFSET 0x10UL

#define TMHTITR_VALUE_STRUCT_NAME TmuTmhtitrValue

MMIO_DECLARE_REG32_VALUE_STRUCT(TMHTITR_VALUE_STRUCT_NAME);

MMIO_DECLARE_REG32_READER(TMU, TMHTITR, TMHTITR_VALUE_STRUCT_NAME,
						  TMU_TMHTITR_OFFSET);

MMIO_DECLARE_REG32_WRITER(TMU, TMHTITR, TMHTITR_VALUE_STRUCT_NAME,
						  TMU_TMHTITR_OFFSET);

// Helper
#define TMHTITR_DECLARE_BIT_FIELD_FNS(bf_name, T)                             \
	TMU_DECLARE_BIT_FIELD_GETTER(TMHTITR, bf_name, TMHTITR_VALUE_STRUCT_NAME, \
								 T, bf_name##_SHIFT, bf_name##_MASK);         \
	TMU_DECLARE_BIT_FIELD_SETTER(TMHTITR, bf_name, TMHTITR_VALUE_STRUCT_NAME, \
								 T, bf_name##_SHIFT, bf_name##_MASK);

#define EN1_SHIFT 31
#define EN1_MASK (0b1u << EN1_SHIFT)
TMHTITR_DECLARE_BIT_FIELD_FNS(EN1, bool);

#define EN0_SHIFT 30
#define EN0_MASK (0b1u << EN0_SHIFT)
TMHTITR_DECLARE_BIT_FIELD_FNS(EN0, bool);

#define TEMP1_SHIFT 16
#define TEMP1_MASK (0xFFu << TEMP1_SHIFT)
TMHTITR_DECLARE_BIT_FIELD_FNS(TEMP1, int8);

#define TEMP0_SHIFT 0
#define TEMP0_MASK (0xFFu << TEMP0_SHIFT)
TMHTITR_DECLARE_BIT_FIELD_FNS(TEMP0, int8);
