#pragma once

#ifndef DRIVERS
#error "This header should only be imported by a driver"
#endif

#include <lib/mmio/mmio_macros.h>
#include <lib/stdbool.h>

#include "uart_macros.h"

// 17.2.14.1 - 7364

#define UART_URXD_OFFSET          0x0UL

#define URXD_VALUE_STRUCT_NAME    UartUrxdValue

MMIO_DECLARE_REG32_VALUE_STRUCT(URXD_VALUE_STRUCT_NAME);

MMIO_DECLARE_REG32_READER(UART, URXD, URXD_VALUE_STRUCT_NAME, UART_URXD_OFFSET);

// It is a read only register, no setter needed

// RX_DATA

#define RX_DATA_SHIFT    0
#define RX_DATA_MASK     (0xFF << RX_DATA_SHIFT)

UART_DECLARE_BIT_FIELD_GETTER(URDX, RX_DATA, URXD_VALUE_STRUCT_NAME, uint8,
			      RX_DATA_SHIFT, RX_DATA_MASK);

// PRERR

#define PRERR_SHIFT    10
#define PRERR_MASK     (0b1 << PRERR_SHIFT)

UART_DECLARE_BIT_FIELD_GETTER(URDX, PRERR, URXD_VALUE_STRUCT_NAME, bool,
			      PRERR_SHIFT, PRERR_MASK);

// BRK

#define BRK_SHIFT    11
#define BRK_MASK     (0b1 << BRK_SHIFT)

UART_DECLARE_BIT_FIELD_GETTER(URDX, BRK, URXD_VALUE_STRUCT_NAME, bool,
			      BRK_SHIFT, BRK_MASK);

// FRMERR

#define FRMERR_SHIFT    12
#define FRMERR_MASK     (0b1 << FRMERR_SHIFT)

UART_DECLARE_BIT_FIELD_GETTER(URDX, FRMERR, URXD_VALUE_STRUCT_NAME, bool,
			      FRMERR_SHIFT, FRMERR_MASK);

// OVRRUN

#define OVRRUN_SHIFT    13
#define OVRRUN_MASK     (0b1 << OVRRUN_SHIFT)

UART_DECLARE_BIT_FIELD_GETTER(URDX, OVRRUN, URXD_VALUE_STRUCT_NAME, bool,
			      OVRRUN_SHIFT, OVRRUN_MASK);

// ERR

#define ERR_SHIFT    14
#define ERR_MASK     (0b1 << ERR_SHIFT)

UART_DECLARE_BIT_FIELD_GETTER(URDX, ERR, URXD_VALUE_STRUCT_NAME, bool,
			      ERR_SHIFT, ERR_MASK);

// CHARRDY

#define CHARRDY_SHIFT    15
#define CHARRDY_MASK     (0b1 << CHARRDY_SHIFT)

UART_DECLARE_BIT_FIELD_GETTER(URDX, CHARRDY, URXD_VALUE_STRUCT_NAME, bool,
			      CHARRDY_SHIFT, CHARRDY_MASK);
